### PR TITLE
Feature/simplify masks

### PR DESCRIPTION
**Pull request by calebzulawski**
Remove explicit bitmasks.

Add `ToBitMask` trait which allows you to convert masks to `u64`.

### CODE REVIEW

**Comment by calebzulawski** [comment]
I'm not sure. I'm still thinking about that.  Unfortunately there's basically no way to represent that in the rust type system as far as generics go.  Related to #50

**Comment by programmerjake** [comment]
> I'm not sure. I'm still thinking about that. Unfortunately there's basically no way to represent that in the rust type system as far as generics go. Related to #50

An idea for fixing that:
https://github.com/rust-lang/stdsimd/issues/50#issuecomment-822634071

**Comment by workingjubilee** [comment]
@programmerjake We will absolutely successfully work out a version that does not break on 2048-bit vectors with byte lanes before we stabilize anything (or else over my dead body, I suppose). You can expect to see this API change a lot, please do not read too much into any single version. Right now, we're trying things out a lot and seeing how things work.

"How to handle masks on platforms" is definitely going to be an Unresolved Question in our RFC.

**Comment by calebzulawski** [comment]
I think there are two separate things here that we need to consider.

One is that masks of any (reasonable) vector length should be supported, regardless of their implementation.  That could be solved by using a trait like that (it may be appropriate as part of `LanesAtMost32` or whatever we end up calling it).

But I think there is a separate problem of explicitly exposing a mask as an integer bitmask.  This is the SSE movemask example, where you use your bitmask as an index to a lookup table or similar.  It's possible to have a 2048-lane vector, but I don't think it's useful to expose an entire 256-byte "integer".  Or, hypothetically, if we support Mask8<65536> in the future, I don't think there's any (portable!) way of exposing that.  On AVX-512 is that 2048 k registers placed into an array in memory?  I can't think of many (portable!) reasons you'd need to access that as a [u8].  This is what the `ToBitMask` trait is for, converting bit masks with up to 64 lanes into `u64`s, independently of the supported number of mask lanes.

**Comment by calebzulawski** [comment]
Anyone know why the MIPS masks seem to be reversed when packed to an integer?  Somehow an LLVM bug or is there something peculiar about MIPS?

**Comment by programmerjake** [comment]
IDK, but maybe it's related to Ada bit array ordering?

**Comment by workingjubilee** [comment]
...Ada bit array?

**Comment by programmerjake** [comment]
> ...Ada bit array?

They describe it some here:
https://en.wikibooks.org/wiki/Ada_Programming/Types/array#With_aliased_elements

**Comment by calebzulawski** [comment]
I think that leaves me with more questions than I started with.  What do Ada arrays have to do with this?

**Comment by programmerjake** [comment]
Well, when discussing which order to have bitmasks in SimpleV, lxo (one of the GCC Ada compiler engineers who's helping out with Libre-SOC) mentioned that Ada uses MSB to LSB ordering for bit arrays -- I figured that might be related since it uses the same order as what you apparently noticed in MIPS.

**Comment by calebzulawski** [comment]
Hmm.  I'd hope that's not related to the problem.  I would expect LLVM to maintain consistent bit field ordering across architectures.

**Comment by workingjubilee** [comment]
Can you rebase this?

**Comment by calebzulawski** [comment]
Okay.  "Simplify" might be a bit of a misnomer now (but the API is definitely simplified!)

I used a `Mask` helper trait to mostly fix #50.  I didn't use `const_evaluatable_unchecked` to implement the trait over all masks, but it should be possible in the future, effectively solving that problem.

Bit masks are now implemented as arrays of `u8` and can be exposed to the users of stdsimd that way, too.  If you want an integer you'll have to do the conversion yourself (not that big of a deal).  Due to limitations in the `simd_bitmask` and `simd_select_bitmask` intrinsic, `Mask` has an extra `IntBitMask` associated type, which is purely used internally.  We should be able to remove that after improving the intrinsics to accept arrays of `u8` as bitmasks as well.

**Comment by workingjubilee** [comment]
This wound up not simplifying things as much as intended internally but it looks much better to me as an external API, really, which is what counts here. Can you add "modify Rust SIMD intrinsics to accept u8-or-something bitmasks" to #46 with a note about all the ones that need to get touched?

**Pull request merged**
